name: ChatOps
on:
  issue_comment:
    # This shouldn't be called for comment deletion
    types:
      - created
      - edited

jobs:
  chatops:
    name: ChatOps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        id: add-comment
        env:
          BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        with:
          script: |
            res = github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Updating ephemeral image and labeling PR for deploy. [See build](${{ env.BUILD_URL }})...'
            })
            console.log(res)
            octokit.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.comment.id,
              "eyes",
            });
      - name: Show result
        run: echo "${{steps.add-comment.outputs.result}}"
      - name: Update comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.updateComment({
              comment_id: ${{steps.add-comment.outputs.result.id}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Updating ephemeral image and labeling PR for deploy... Done!'
            })
          result-encoding: string
