name: On Label

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'ephemeral_env' }}
    runs-on: ubuntu-latest

    steps:
      - name: "add comment"
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'You have added the label ${{ github.event.label.name }}; You are on branch ${{ github.head_ref }}'
            })
